language: python

matrix:
  include:
      - python: 3.6
        dist: trusty
        sudo: false
      - python: 3.7
        dist: xenial
        sudo: true

before_install:
    - python --version
    - pip install --upgrade pip
    - pip install -U pytest
    - pip install codecov

install:
    - pip install ".[test]"

script:
   - pytest tests/ --cov=hgc

after_success:
   - codecov